name: 01 - Building blocks

on:
  workflow_dispatch: 

jobs:
  echo-hello:
    name: Hello Job
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello"
        run: |
          echo "Say Hello"
  echo-goodbye:
    name: goodbye job
    runs-on: ubuntu-latest
    steps:
      - name: Successful step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say goodbye
        run: |
          echo "Goodbye!!"
        


