name: Building blocks

on:
  push:
  workflow_dispatch: 

jobs:
  echo-hello:
    name: Hello Job
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello"
        run: |
          echo "Say Hello"
  echo-goodbye:
    name: goodbye job
    runs-on: ubuntu-latest
    steps:
      - name: Passed step
        run: |
          echo "I will Pass"
          exit 0
      - name: Say goodbye
        run: |
          echo "Goodbye!!"
        


