name: 02 - Worflow Events

on:
  #push:
  #pull_request:
  workflow_dispatch:
  schedule: 
    - cron: "26 19 * * *"
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the event trigger
        run: |
          echo "event name: ${{ github.event_name }}"
