name: 02 - Worflow Events

on:
  #push:
  #pull_request:
  workflow_dispatch:
  # schedule: 
  #   - cron: "*/5 * * * *"
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the event trigger
        run: |
          echo "I've been triggered by a(n) ${{ github.event_name }} event"
