name: 03 - Workflow Runners

on:
  workflow_dispatch:
  #push:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on a ubuntu runner."
          echo "The OS for this runner is: $RUNNER_OS"

  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "This job is running on a windows runner."
          echo "The OS for this runner is: ${{ runner.os }}"

  # mac-echo:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Show OS
  #       shell: bash
  #       run: |
  #         echo "This job is running on a Mac runner."
  #         echo "The OS for this runner is: ${{ runner.os }}"