name: 04 - Using Actions

on:
  push:

jobs:
  build:
    name: build using action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Printing Folders
        run: |
          echo "this folder structure is:"
          ls . -laR
