name: 06 - Contexts

on:
  push:
  workflow_dispatch: 

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Github event name: ${{ github.event_name }}"
          echo "Github Ref: ${{ github.ref }}"
          echo "Github SHA: ${{ github.sha }}"
          echo "Github actor: ${{ github.actor }}"
          echo "Github Workflow: ${{ github.workflow }}"
          echo "Github Run ID: ${{ github.run_id }}"
          echo "Github Run Number: ${{ github.run_number }}"
      - name: Retrieve Variable
        run: |
          echo "content for MY_VAR: ${{ vars.MY_VAR }}"
        
          