name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'Off' }}

on:
  push: 
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false
  
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: "Debug checker - print startup data - ${{ inputs.debug && 'debug enabled' || 'debug disabled' }}"
        if: ${{ inputs.debug == true }}
        #if: inputs.debug == true   --> IT ALSO WORKS THIS WAY
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "sha: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: "[${{ inputs.debug }}] - Print when triggered from main"
        if: ${{ inputs.debug == true && github.ref_name  == 'main' }}
        #if: inputs.debug == true && github.ref_name  == 'main'   --> IT ALSO WORKS THIS WAY
        
        run: |
          echo "I was triggered by branch main"
          
      - name: Greetings
        run: echo "Hello World"


