name: 07 - Using Expressions

on:
  push: 
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false
  
jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: "Debug checker - print startup data - ${{ inputs.debug }}"
        if: ${{ inputs.debug == true }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "sha: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: "[${{ inputs.debug }}] - Print when triggered from main"
        if: ${{ inputs.debug == true && github.ref_name  == 'main' }}
        run: |
          echo "I was triggered
      - name: Greetings
        run: echo "Hello World"


