name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'Off' }}

on:
  push: 
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false

# Se below an example of setting a deafult value for a var definition that has the chance of coming as empty/null
# Read the || as kinda "otherwise, in this case it's not a OR operator"
env:
  MY_VAR_WITH_DEFAULT: ${{ vars.MY_VAR || 'default_value' }} 


jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: "Debug checker - print startup data - ${{ inputs.debug && 'debug enabled' || 'debug disabled' }}"
        if: ${{ inputs.debug }}
        # for boolean checks, only the variable inside an IF is enough for checking if it's true
        #if: inputs.debug == true   --> IT ALSO WORKS THIS WAY
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "sha: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: "[Debug] - Print when triggered from main"
        if: ${{ inputs.debug && github.ref_name  == 'main' }}
        #if: inputs.debug && github.ref_name  == 'main'   --> IT ALSO WORKS THIS WAY
        #if: inputs.debug && github.ref  == 'refs/heads/main'   --> IT ALSO WORKS THIS WAY
        
        run: |
          echo "I was triggered by branch main"
          
      - name: Greetings
        run: echo "Hello World"


