name: 08 - Using Variables

on:
  #push:
  workflow_dispatch: 

env:
  WORKFLOW_VAR: "I'm a workflow env var"
  OVERWRITTEN: "I'll be overwritten"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I'm a job env var"
      OVERWRITTEN: "I've been overwritten at the job level"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I'm a step env var"
          step_var2: "I'm another step env var"
         # OVERWRITTEN: "I've ovewritten at the step level"  
        run: |
          echo "Step env var: ${{ vars.STEP_VAR }}"
          echo "Step env var2: ${{ vars.step_var2 }}"
          echo "Job env var: ${{ vars.JOB_VAR }}"
          echo "Workflow env var: ${{ vars.WORKFLOW_VAR }}"
          echo "Overwritten env var: ${{ vars.OVERWRITTEN }}"
      
      - name: OverWrite Job Variable
        env: 
          OVERWRITTEN: 'I have been overwritten at the step level'
        run: |
          echo "Step env var: ${{ vars.OVERWRITTEN }}"

