name: 09 - Using Functions

on:
  pull_request: 
  workflow_dispatch: 

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print the PR title
        run: echo ${{ github.event.pull_request.title }}
      
      - name: Print the PR labels
        run: |
          cat << EOF
          ${{ toJson(github.event.pull_request.labels) }}
          EOF

      - name: Bug Step
        if: ${{ ! cancelled() && contains(github.ever.pull_request.title, 'fix') }}
        run: echo I am a bug fix

      - name: Sleep for 20 seconds
        run: sleep 20

      - name: Failing Step
        run: exit 1

      - name: I will be skipped
        if: success()
        run: echo I will print if the previous steps succeed

      - name: I will execute
        if: failure()
        run: echo I will print if any previous step fails.

      - name: I will execute
        if:  ${{ ! cancelled() }}
        run: echo I will always print, except if the workflow is cancelled.

      - name: I will execute when cancelled
        if: cancelled()
        run: echo I will execute when cancelled
