name: 10 - Controlling the Execution Flow
run-name: "10 - Controlling the Execution Flow - Unit tests: ${{ inputs.pass-unit-tests && 'Enabled' || 'Disabled' }}"

on:
  workflow_dispatch: 
    inputs:
      pass-unit-tests:
        type: boolean
        default: false

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and build
        run: |
          echo "Linting and building project"

  unit-tests:
    runs-on: ubuntu-latest
    env:
      UNIT_TESTS_STATUS: ${{ inputs.pass-unit-tests.value }}
    steps:
      - name: Running unit tests
        if: ${{ inputs.pass-unit-tests }}
        run: |
          echo "pass-unit-tests inputs is set to $UNIT_TESTS_STATUS"
          echo "Running tests..."
      - name: Failing tests
        if: ${{ !inputs.pass-unit-tests }}
        run: |
          echo Test failed
          exit 1

  deploy-nonprod:
    runs-on: ubuntu-latest
    needs:
      - lint-build
      - unit-tests
    steps:
      - name: Deploying to non-prod
        run: |
          echo "Deploying to non-prod..."

  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: Running E2E tests
        run: |
          echo "Running E2E tests..."

  load-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: Running E2E tests
        run: |
          echo "Running E2E tests..."

  deploy-prod:
    runs-on: ubuntu-latest
    needs: 
      - e2e-tests
      - load-tests
    steps:
      - name: Deploying to Prod
        run: |
          echo "Deploying to Prod..."