name: 11 - Working with Inputs

on:
  workflow_dispatch: 
    inputs: ## available types are: string, number, choice, boolean and environment
      dry-run:
        type: boolean
        description: "Skip deployment and only print build output"
        default: false
      target:
        type:  environment ## it will produce a dropbos with the available environments created at the repo configuration level
        required: true
        description: "Which environment the workflow will target"
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        description: "Release from which to build and deploy"
        default: v3


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "Building from tag ${{ inputs.tag }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !inputs.dry-run }}
    env:
      ENV_INPUT: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: |
          echo "Deploying to $ENV_INPUT"

