name: 12 - Working with Outputs

on:
  workflow_dispatch: 
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        description: Build Status
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo "the value of the GITHUB_OUTPUT variable is: $GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
          echo the value of the GITHUB_OUTPUT variable is: $(cat $GITHUB_OUTPUT)


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: |
          echo Deploying
