name: 12 - Working with Outputs - Extended

on:
  workflow_dispatch: 
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        description: Build Status
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo "the value of the GITHUB_OUTPUT variable is: $GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
          echo "output1=value1" >> $GITHUB_OUTPUT
      - name: Steps with mistake
        run: |
          echo "the value of the GITHUB_OUTPUT variable is: $GITHUB_OUTPUT"
          echo "output2=value2" >> $GITHUB_OUTPUT
          echo the value of the GITHUB_OUTPUT variable is: $(cat $GITHUB_OUTPUT)
          echo "mistake=true" > $GITHUB_OUTPUT
          echo the value of the GITHUB_OUTPUT variable is: $(cat $GITHUB_OUTPUT)


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    #if: needs.build.outputs.build-status == 'success' --> can be in this format too
    steps:
      - name: Deploy
        run: |
          echo Deploying
      - name: Print Outputs
        run: echo ${{ needs.build.outputs.output1 }}
