name: 15 - Working with Matrices

on:
  workflow_dispatch: 

jobs:
  backwards-compatibility:
    name: "${{ matrix.operational-systems }} - ${{ matrix.node-versions }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true ## if a job fails the upcoming ones, that have not started yet will be cancelled
      matrix:
        node-versions:
          - 18.x
          - 20.x
          - 21.x
        operational-systems:
          - ubuntu-latest
          - windows-latest
        include:
          - operational-systems: ubuntu-latest
            node-versions: 16.x
          - operational-systems: ubuntu-latest
            node-versions: 21.x
            tag: experimental
        
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Perform some tests
        run: |
          echo "running tests on OS ${{ matrix.operational-systems }} and NodeJS ${{ matrix.node-versions }}, the tag is ${{ matrix.tag || 'default' }}"
          sleep 10

      - name: Upload test results
        run: echo uploading test results...

      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: exit 1
      
      - name: Setting Job to success status
        if: ${{ !cancelled() }}
        run: echo masking the job result