name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch: 
    inputs:
      url:
        default: 'https://www.google.com'

jobs:
  ping-url:
    runs-on: ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with: ${{ inputs.url }}

